# Auto-generated by Runix AI Agent
# Task: take a screenshot
# Generated: 2025-06-20T21:12:24.607Z
# Success: YES
# Iterations: 1/2

Feature: AI Agent Recorded Workflow - take a screenshot
  As an automation engineer
  I want to replay the AI agent's recorded actions
  So that I can reproduce the same workflow consistently

  @ai-recorded @replay
  Scenario: Replay AI Agent Task - take a screenshot
    # Original AI task: take a screenshot
    # Execution completed: Successfully
    
    # === Verification ===
    Then the workflow should be completed
    And the task "take a screenshot" should be successful
