# Auto-generated by Runix AI Agent
# Task: take a screenshot
# Generated: 2025-06-20T22:27:34.391Z
# Success: YES
# Iterations: 2/2

Feature: AI Agent Recorded Workflow - take a screenshot
  As an automation engineer
  I want to replay the AI agent's recorded actions
  So that I can reproduce the same workflow consistently

  @ai-recorded @replay
  Scenario: Replay AI Agent Task - take a screenshot
    # Original AI task: take a screenshot
    # Execution completed: Successfully
    
    # === Iteration 1 ===
    When I take a screenshot "iteration-1-start.png"
    And I press key "PrintScreen"
    And I wait for 2 seconds  # Post-action delay
    And I take a screenshot "iteration-1-end.png"

    # === Verification ===
    Then the workflow should be completed
    And the task "take a screenshot" should be successful
