# Auto-generated by Runix AI Agent
# Task: Press PrintScreen key
# Generated: 2025-06-21T08:59:52.230Z
# Success: YES
# Iterations: 2/5

Feature: AI Agent Recorded Workflow - Press PrintScreen key
  As an automation engineer
  I want to replay the AI agent's recorded actions
  So that I can reproduce the same workflow consistently

  @ai-recorded @replay
  Scenario: Replay AI Agent Task - Press PrintScreen key
    # Original AI task: Press PrintScreen key
    # Execution completed: Successfully
    
    # === Iteration 1 ===
    When I take a screenshot "iteration-1-start.png"
    And I press key "PrintScreen"
    And I wait for 2 seconds  # Post-action delay
    And I take a screenshot "iteration-1-end.png"

    # === Verification ===
    Then the workflow should be completed
    And the task "Press PrintScreen key" should be successful
