# Auto-generated by Runix AI Agent
# Task: Take a screenshot of the desktop
# Generated: 2025-06-21T07:30:38.625Z
# Success: YES
# Iterations: 2/5

Feature: AI Agent Recorded Workflow - Take a screenshot of the desktop
  As an automation engineer
  I want to replay the AI agent's recorded actions
  So that I can reproduce the same workflow consistently

  @ai-recorded @replay
  Scenario: Replay AI Agent Task - Take a screenshot of the desktop
    # Original AI task: Take a screenshot of the desktop
    # Execution completed: Successfully
    
    # === Iteration 1 ===
    When I take a screenshot "iteration-1-start.png"
    And I press key "PrintScreen"
    And I wait for 2 seconds  # Post-action delay
    And I take a screenshot "iteration-1-end.png"

    # === Verification ===
    Then the workflow should be completed
    And the task "Take a screenshot of the desktop" should be successful
